    # waktutc=db.execute(text("Select Waktu from data_prediksi WHERE ID=:id"),{"id":id}).fetchall()
    # ID_kebuntc=db.execute(text("Select  ID_Kebun from data_prediksi WHERE ID=:id"),{"id":id}).fetchall()
    # User_IDtc=db.execute(text("Select   UserID from data_prediksi WHERE ID=:id"),{"id":id}).fetchall()
    # Nama_Filetc=db.execute(text("Select Nama_File from data_prediksi WHERE ID=:id"),{"id":id}).fetchall()
    # Hasil_Prediksitc=db.execute(text("Select Hasil_Prediksi from data_prediksi WHERE ID=:id"),{"id":id}).fetchall()
